# Generated by Django 4.2.6 on 2023-10-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
    ]
