# Generated by Django 4.2.5 on 2023-10-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookRate',
        ),
    ]
