# Generated by Django 4.2.6 on 2023-10-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writersjam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
